### PR TITLE
USB Controller call fix for Android14

### PR DESCRIPTION
**Pull request by ikhoeyZX**
Fix USB controller intent not triggering in Android 14

Screenshot_20240614_190251_Settings

### CODE REVIEW

**Comment by Macdu** [comment]
Thanks! Is this only part of the latest SDL update ?

**Comment by ikhoeyZX** [comment]
> Thanks! Is this only part of the latest SDL update ?

yes
need update to SDL2 v2.30.0

**Comment by Macdu** [comment]
The USB controller fix (which comes from you) isn't part of the latest release (2.30.4), on your SDL PR, it is marked for 2.32. If you want you can just put this part in this PR. I'll update to the latest SDL version on my own for the next release.

**Comment by ikhoeyZX** [comment]
moved to
https://github.com/Vita3K/Vita3K-Android/pull/660

**Pull request closed without merging**
